services:

  cells:
    image: pydio/cells:latest
    restart: unless-stopped
    ports:
      - "8200:8080"
    volumes: 
      - ./cellsdir:/var/cells
      - ./data:/var/cells/data

  mysql:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: P@ssw0rd
    volumes:
      - ./mysqldir:/var/lib/mysql
